# Generated by Django 3.2.19 on 2023-06-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_room_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='likes',
        ),
        migrations.AddField(
            model_name='room',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
