# Generated by Django 3.2.19 on 2023-06-28 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20230628_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='likes',
            field=models.ManyToManyField(related_name='liked_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
