# Generated by Django 3.2.19 on 2023-06-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20230628_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='likes',
        ),
    ]
