# Generated by Django 3.2.19 on 2023-07-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_message_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
