# Generated by Django 3.2.19 on 2023-08-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_roommember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lessons',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='RoomMember',
        ),
    ]
